#!/bin/sh
# Synthé 3 - A speech synthetizer software for french
#
# Copyright (C) 1985-2015 by Michel MOREL <michel.morel@unicaen.fr>.
#
# Synthé 3 comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: https://github.com/acceslibreinfo/synthe3
#
# This software is maintained by Shérab <Sebastien.Hinderer@ens-lyon.org>.

SYNTHE3_DIR=`dirname "${0}"`
export LD_LIBRARY_PATH=${SYNTHE3_DIR}
export SYNTHE3_SEGFILE=${SYNTHE3_DIR}/Michel.seg
export SYNTHE3_TABFILE=${SYNTHE3_DIR}/Synthe.tab
exec ${SYNTHE3_DIR}/synthe3 "$@"
